plugin: community.vmware.vmware_vm_inventory
hostname: "{{ lookup('env','VCENTER_HOST') }}"
username: "{{ lookup('env','VCENTER_USER') }}"
password: "{{ lookup('env','VCENTER_PASS') }}"
validate_certs: false
with_tags: true
